### ISSUE TITLE
Update pypi release

### ISSUE THREAD

**Issue by cwfink** [ucbpylegroup/QETpy#10]

**Comment by cwfink** [comment]
Actually, should we change the version number to 1.0.0 since the latest updates are not backwards compatible? 

See:
https://semver.org/

**Comment by slwatkins** [comment]
This works for me, let's move to version 1.0.0 and follow those conventions from now on.

**Comment by cwfink** [comment]
Updated PyPi with version 1.0.0

https://pypi.org/project/QETpy/1.0.0/

**Comment by cwfink** [comment]
We should also tag a release on GitHub as well with the same dist. That way we can version control the documentation for v1.0.0. 

I'll do this later today

**Comment by slwatkins** [comment]
I went ahead and tagged the release for v1.0.0, so I'll close this.
