### ISSUE TITLE
Add baseline subtraction option for plotting in OFnonlin

### ISSUE THREAD

**Issue by slwatkins** [ucbpylegroup/QETpy#14]
Since OFnonlin already calculates the offset, it would be nice for the plotting function to use it for baseline subtraction so that the user no longer would need to do the baseline subtraction themselves.

**Comment by cwfink** [comment]
Done

e851b828656eed9f2f16ecdf250ddb4fdc8f74d9

**Comment by slwatkins** [comment]
Reopening this issue, as it was accidentally removed in PR #19.

**Comment by cwfink** [comment]
Fixed. Again. https://github.com/ucbpylegroup/QETpy/blob/master/qetpy/plotting/_plotting.py
