### ISSUE TITLE
Update Readthedocs to point to ucbpylegroup/QETpy

### ISSUE THREAD

**Issue by slwatkins** [ucbpylegroup/QETpy#15]
Readthedocs currently points to berkeleycdms/QETpy, which I believe causes the build to fail. Also, the front page of the documentation references the old name. This should all be updated.

**Comment by cwfink** [comment]
Changed the reference in RTD to point to new group name 
2a582690ec9aefc9d7f9d351fdb7fcc6f01bd9d2

Also, changed some settings on the RTD project so it now compiles. It seemed to be unrelated to the change in group name.
