### ISSUE TITLE
Improve demos

### ISSUE THREAD

**Issue by cwfink** [ucbpylegroup/QETpy#16]
We should add more demos to give examples for more of the functionality of QETpy. 

Demos for:
-optimum filter
-pileup of

**Comment by cwfink** [comment]
The two I mentioned above could all be part of the same demo I made for OFnonlin

**Comment by slwatkins** [comment]
Would also be good to use the `gen_noise` function with a random seed, so that we don't need to provide any data files.

**Comment by cwfink** [comment]
Added demo for fitting a pulse with ```ofamp``` and with ```OFnonlin```

I'll let @slwatkins add a demo for the pileup OF. This should possibly go in a different notebook the the above

5bc80608848804500a39383a79721ea3a189d664

**Comment by slwatkins** [comment]
Fitting demo was improved in PR #32, so I'll close this.
