### ISSUE TITLE
Add positive (or negative) pulse constraint option to OptimumFilter

### ISSUE THREAD

**Issue by slwatkins** [ucbpylegroup/QETpy#21]
For the `OptimumFilter`, an option should be added that constrains the possible fitted amplitudes to only positive (or negative, depending on which direction is physical). This is done by simply not allowing to OF to choose a fit with the opposite direction.

**Comment by cwfink** [comment]
This was addressed by @slwatkins in PR https://github.com/ucbpylegroup/QETpy/pull/25, so I am closing this issue
