### ISSUE TITLE
Fitting demo is out of date

### ISSUE THREAD

**Issue by slwatkins** [ucbpylegroup/QETpy#31]
The [fitting demo](https://github.com/ucbpylegroup/QETpy/blob/master/demos/fitting/pulse_fitting_example.ipynb) shows how to use `qetpy.OFnonlin`. However, the method `qetpy.OFnonlin.fit_falltimes` calls the optional argument `lgcdouble`, which was replaced by `npolefit` in PR #19.

This should also be updated on the readthedocs demo, which would need to be recompiled.

**Comment by cwfink** [comment]
After this is corrected, we should probably make another release on PyPi as `QETpy` is getting fairly stable at this point

**Comment by slwatkins** [comment]
Dealt with in PR #32.

**Comment by cwfink** [comment]
Fixed with PR  https://github.com/ucbpylegroup/QETpy/pull/32
