### ISSUE TITLE
Change OFnonlin Functions for three and four pole fits

### ISSUE THREAD

**Issue by slwatkins** [ucbpylegroup/QETpy#33]
We should change the three/four pole fit functional forms.

Currently, the functional form for the three pole fit is:

![](https://latex.codecogs.com/gif.latex?%5Cdpi%7B100%7D%20f%28t%29%20%3D%20A%281-%5Cmathrm%7Be%7D%5E%7B-t/%5Ctau_1%7D%29%5Cmathrm%7Be%7D%5E%7B-t/%5Ctau_2%7D%20&plus;%20B%5Cmathrm%7Be%7D%5E%7B-t/%5Ctau_3%7D)

However, we know that we have the constraint that ![](https://latex.codecogs.com/gif.latex?%5Cdpi%7B80%7D%20f%280%29%3D0).

This would give:

![](https://latex.codecogs.com/gif.latex?%5Cdpi%7B100%7D%20f%280%29%3D0%20%5Cimplies%200%20%3D%20A%281-1%29*1%20&plus;%20B*1%20%3D%20B)

Thus, the current functional form for the three pole fit appears to be nonphysical. A better form could be:

![](https://latex.codecogs.com/gif.latex?%5Cdpi%7B100%7D%20f%28t%29%20%3D%20A%5Cmathrm%7Be%7D%5E%7B-t/%5Ctau_1%7D%20&plus;%20B%5Cmathrm%7Be%7D%5E%7B-t/%5Ctau_2%7D%20-%20C%5Cmathrm%7Be%7D%5E%7B-t/%5Ctau_3%7D)

Which simplifies to the following, after using ![](https://latex.codecogs.com/gif.latex?%5Cdpi%7B80%7D%20f%280%29%3D0).

![](https://latex.codecogs.com/gif.latex?%5Cdpi%7B100%7D%20f%28t%29%20%3D%20A%5Cmathrm%7Be%7D%5E%7B-t/%5Ctau_1%7D%20&plus;%20B%5Cmathrm%7Be%7D%5E%7B-t/%5Ctau_2%7D%20-%20%28A&plus;B%29%5Cmathrm%7Be%7D%5E%7B-t/%5Ctau_3%7D)

For the four pole fit, the functional form is:

![](https://latex.codecogs.com/gif.latex?%5Cdpi%7B100%7D%20f%28t%29%20%3D%20A%281-%5Cmathrm%7Be%7D%5E%7B-t/%5Ctau_1%7D%29%5Cmathrm%7Be%7D%5E%7B-t/%5Ctau_2%7D%20&plus;%20B%5Cmathrm%7Be%7D%5E%7B-t/%5Ctau_3%7D%20&plus;%20C%5Cmathrm%7Be%7D%5E%7B-t/%5Ctau_4%7D)

If we use the same constraint ![](https://latex.codecogs.com/gif.latex?%5Cdpi%7B80%7D%20f%280%29%3D0), we then have that _B = -C_, giving:

![](https://latex.codecogs.com/gif.latex?%5Cdpi%7B100%7D%20f%28t%29%20%3D%20A%281-%5Cmathrm%7Be%7D%5E%7B-t/%5Ctau_1%7D%29%5Cmathrm%7Be%7D%5E%7B-t/%5Ctau_2%7D%20&plus;%20B%28%5Cmathrm%7Be%7D%5E%7B-t/%5Ctau_3%7D%20-%20%5Cmathrm%7Be%7D%5E%7B-t/%5Ctau_4%7D%29)

Now, this appears to be an extra rise time, instead of the desired extra fall time. Perhaps, instead, it should be something like:

![](https://latex.codecogs.com/gif.latex?%5Cdpi%7B100%7D%20f%28t%29%20%3D%20A%5Cmathrm%7Be%7D%5E%7B-t/%5Ctau_1%7D%20&plus;%20B%5Cmathrm%7Be%7D%5E%7B-t/%5Ctau_2%7D%20&plus;%20C%5Cmathrm%7Be%7D%5E%7B-t/%5Ctau_3%7D%20-%20D%5Cmathrm%7Be%7D%5E%7B-t/%5Ctau_4%7D)

Where _f(0)=0_ gives _D = A + B + C_.

On the other hand, maybe we should throw out this code for a more general nonlinear fit. Either way, I've linked the relevant code below:

https://github.com/ucbpylegroup/QETpy/blob/534f3114587bb6cb9f0c8efc3f9909ee203d185d/qetpy/core/_fitting.py#L1269-L1422

**Comment by nick-mast** [comment]
This was resolved in #36.
