### ISSUE TITLE
Add bounds option to OFnonlin.fit_falltimes

### ISSUE THREAD

**Issue by nick-mast** [ucbpylegroup/QETpy#40]
fit_falltimes currently has fit parameter bounds hard-coded as fractions/multiples of the initial guess values. It would be good to allow the user the option to specify the bounds.

**Comment by cwfink** [comment]
I agree. I think first step would be to add option for user defined bounds, then this should be done automatically in a 'smart' way. ie, there should be some scaling of the fall time bounds based on the pulse hight.

**Comment by cwfink** [comment]
added with PR https://github.com/ucbpylegroup/QETpy/pull/48
