### ISSUE TITLE
Change 2-pole amplitude parameter in OFnonlin

### ISSUE THREAD

**Issue by nick-mast** [ucbpylegroup/QETpy#49]
The 3,4 pole fit functions have amplitude parameters A,B,C which appear naturally in the pulse functional forms and integral expressions, though they are related to the pulse height in a complicated (non-analytic) manner.

![image](https://user-images.githubusercontent.com/38258797/54303873-3099e300-4581-11e9-956e-d987199fbe88.png)
![image](https://user-images.githubusercontent.com/38258797/54303913-4a3b2a80-4581-11e9-8e55-dd7be9f78a88.png)

The 2-pole expression currently takes the pulse height as an input and internally calculates the amplitude parameter A which is used in the fit. This calculation can fail if the rise and fall times are equal. For this reason, and for compliance with the 3,4 pole fits, I think we should change the 2-pole functional form to take the parameter A as an input

**Comment by cwfink** [comment]
Implemented in PR https://github.com/ucbpylegroup/QETpy/pull/63
