### ISSUE TITLE
Fix t0 shift in time-domain template forms in OFnonlin

### ISSUE THREAD

**Issue by nick-mast** [ucbpylegroup/QETpy#50]
The time-domain calculation of 2,3,4-pole pulses first calculates the pulse shape with t0=0, then shifts the pulse to t0 using np.roll
https://github.com/ucbpylegroup/QETpy/blob/f7aa972d5be1009149a5a94f12c0fa858a367a2c/qetpy/core/_fitting.py#L1401

This can be a problem if the pulse has long fall times which extend beyond the end of the trace as they will be wrapped around to the prepulse region. We can fix this by setting all values before t_0 to 0 after the roll.

**Comment by slwatkins** [comment]
There is a `rqpy.shift` function in RQpy, which does exactly this. We should move it over to QETpy, it makes more sense for it to be here anyways.

https://github.com/ucbpylegroup/RQpy/blob/master/rqpy/core/_pulse.py#L10-L49

**Comment by cwfink** [comment]
Added `shift` and `make_template` with Commit https://github.com/ucbpylegroup/QETpy/commit/1fcb99fa1217303ca9d257afb00068f38e76ec46

**Comment by cwfink** [comment]
@nick-mast, do you want to make the change from `np.roll` to `qp.utils.shift()`? I don't want to mess anything up if you are working on other dev changes. Note, `qp.utils.shift()` assumes you are shifting a pulse that is centered. If starting from time zero, this needs to be accounted for.

**Comment by nick-mast** [comment]
You can go ahead if it's not a hassle. I don't have anything else going right now.

**Comment by cwfink** [comment]
Fixed with PR https://github.com/ucbpylegroup/QETpy/pull/63
