### ISSUE TITLE
Noise.calculate_uncorr_noise method does not run if CSD was not calculated first

### ISSUE THREAD

**Issue by slwatkins** [ucbpylegroup/QETpy#53]
The `qetpy.Noise.calculate_uncorr_noise` method does not calculate the uncorrelated noise if the CSD was not calculate. Instead, it calculates the CSD and exits. The reason is because of the code that does this is in the `else` statement. I believe simply moving the code from the `else` block to the main part of the method should be fine.

https://github.com/ucbpylegroup/QETpy/blob/b2fec900635cbc75ba6814964f527e786a0a17fd/qetpy/core/_noise.py#L342-L360

**Comment by cwfink** [comment]
Addressed with PR https://github.com/ucbpylegroup/QETpy/pull/56
