### ISSUE TITLE
Noise plotting function uses attribute not set by Noise class

### ISSUE THREAD

**Issue by slwatkins** [ucbpylegroup/QETpy#54]
The plotting function `_plot_decorrelated_noise` uses an attribute `name` that does not get set by the `qetpy.Noise` class. Should we just make it an optional argument?

https://github.com/ucbpylegroup/QETpy/blob/b2fec900635cbc75ba6814964f527e786a0a17fd/qetpy/plotting/_plotting.py#L40

**Comment by cwfink** [comment]
Addressed with PR https://github.com/ucbpylegroup/QETpy/pull/56
