### ISSUE TITLE
Timeshift for DIDV fit

### ISSUE THREAD

**Issue by ytcs** [ucbpylegroup/QETpy#83]
Sometimes the DIDV data we take has a time offset. This throws off the didv fitter:
![image](https://user-images.githubusercontent.com/19544681/74577040-44448b00-4f42-11ea-8dfc-c3862f3712ac.png)

If I manually offset the traces, then I can get a fit:
![image](https://user-images.githubusercontent.com/19544681/74576979-0b0c1b00-4f42-11ea-8bb5-242d9665980b.png)

Just wondering if there is a better way to do this... Simplest thing to do is just to add another parameter to the DIDV function to let user manually input the offset. But maybe we can fit the absolute value of Z in order to be agnostic to the time offset?

**Comment by slwatkins** [comment]
There is a better way! In the initialization of the `DIDV` class, there is an optional kwarg `dt0`, which sets the guess for the time shift value. By default, it's `10.0e-6`, so you should set this to what the value of the expected time shift, and then the optimization algorithm will find the time offset best fit value starting from that point.

Here's the initialization of the class:

https://github.com/ucbpylegroup/QETpy/blob/ad6ccc2b7711f5429d6d392cea4ee8a030cedc13/qetpy/core/_didv.py#L1304-L1307

And here's a snippet from the docstring, explaining the `dt0` kwarg:

https://github.com/ucbpylegroup/QETpy/blob/ad6ccc2b7711f5429d6d392cea4ee8a030cedc13/qetpy/core/_didv.py#L1349-L1354

How does that work for you? Perhaps this is something we should explicitly add to the DIDV demo, just to make it clearer that this is an option.

**Comment by ytcs** [comment]
Cool! I didn't notice this option before. Good to know it's already in the code.
