### ISSUE TITLE
Add priors fitting to the non-Irwin fitting functions

### ISSUE THREAD

**Issue by slwatkins** [ucbpylegroup/QETpy#90]
Currently, priors fitting only exists for the 2-pole Irwin function in the dIdV fitting code. It would be better to have this generalized for all models.

**Comment by cwfink** [comment]
@slwatkins For the '3-pole' Maasilta model, which model is being used? There are 3: hanging, intermediate, parallel. I think it is the hanging? Regardless, if we are going to use this 3-pole model, should we really have all three options? I think that in the parameterization done in DIDV, the models would be the same, but the meaning of the parameters in terms of TES values would be different

**Comment by slwatkins** [comment]
@cwfink The way it's parameterized, the same functional form applies to all three using the small signal parameters that we have. That is, the differences between those three models Maasilta are in the definition of the loop gain `l` and the definition of what I call `gratio`. So, I think we're good...

**Comment by nkurinsky** [comment]
yeah agreed, the functional form of the fit is equivalent. It would be nice to extract effective parameters for each case but not required

**Comment by slwatkins** [comment]
Are you saying that you want to extract what the different thermal conductances could be for each 3 pole model? Given the assumptions that would have to be made, I would feel better making the user do that themselves.

**Comment by cwfink** [comment]
Yeah, the functional form is the same, I was suggesting that we extract the different conductances, but I agree that maybe this isn't the best place to do it. From a noise point of view, it would be nice to have things in that form, but maybe some other piece of code should do this

**Comment by nkurinsky** [comment]
well for the hanging model, for example, you only need to do one extra step, just the gratio. For the other two i do think it's slightly more complex, but the L/R and beta for example should still be independent of the G/loop gain parameters. So you could provide the hanging model and just a hook to point people to the Maasilta paper for the other interpretations.

**Comment by slwatkins** [comment]
I'm not sure we're all on the same page, I'm saying that the 3-pole parameterization is:

![CodeCogsEqn](https://user-images.githubusercontent.com/35979561/85452227-86fd1c00-b54f-11ea-97e9-00554affd4fe.png)

where the loop gain `\mathcal{L}`, `g_ratio`, `tau_0`, and `tau_3` values have different definitions, based on the different models (hanging, intermediate, parallel). So, `beta`, `L`, `R_0`, `R_p`, `R_sh` will all be returned.

Anyways, what I was saying that, in this parameterization, I don't think it would be useful to add functions to convert `\mathcal{L}`, `g_ratio`, `tau_0`, and `tau_3` to their constituent parameters, as there are lots of assumptions and outside data needed (G, P_0, T_c,  C, what model to use), so I think having it here would be overly complicated.
