### ISSUE TITLE
Rename 2-pole and 3-pole models in DIDV fitting?

### ISSUE THREAD

**Issue by cwfink** [ucbpylegroup/QETpy#96]
In our group we typically label the different TES models based on the the number of poles in the TES response. However, it seems that most of the rest of the TES community refers to different models based on how many heat capacities you have. So in our case, the '2-pole' is a single heat capacity, the '3-pole' would be two heat capacities in 3 different configurations, and there are a few common 3 heat capacity models as well. 

This can potentially cause a bit of misunderstanding if other groups use our code. Should we change our naming conventions to be more reflective of the thermal models?

**Comment by slwatkins** [comment]
So would '1-pole' be zero heat capacities? We could also just add in the documentation what each pole corresponds to in terms of heat capacities. I think I already have in there what the actual models are, so maybe that's enough?

**Comment by nkurinsky** [comment]
That's a weird way to think about it but that's probably correct...it's what you get when you set tau = C/G = 0 for the TES, right?

**Comment by slwatkins** [comment]
That's why I like the 1-, 2-, 3-pole thing we're doing, since then we don't have a weird "zero" heat capacity case. But I think it would be the case of G = 0 without putting any thought into it haha.

**Comment by cwfink** [comment]
Yeah, I think what is there is likely fine, I was just bringing it up since it just seems to be more our own internal jargon. But regardless, if we were to change, there could just be a distinction between the 1-pole and the rest of the models by calling it 'SC' or 'Normal' or something.

**Comment by slwatkins** [comment]
Well, I think that our group tends to force our internal jargon on everyone else, so it would be par for the course to keep it as is.

I do like the 1-, 2-, 3-poles jargon, just because it's pretty simple to pass 1, 2, or 3 to the `dofit` method when fitting. If we change it to heat capacities, then I'm not sure what the best input would be to that function, not a huge fan of passing strings.
